static func _static_init() -> void:
	WhiteboardManager.register_tool(preload("BrushTool.gd"))
	WhiteboardManager.register_tool(preload("EraserTool.gd"))
	WhiteboardManager.register_tool(preload("LineTool.gd"))
	WhiteboardManager.register_tool(preload("CircleTool.gd"))
	WhiteboardManager.register_tool(preload("FilledCircleTool.gd"))
	WhiteboardManager.register_tool(preload("RectangleTool.gd"))
	WhiteboardManager.register_tool(preload("FilledRectangleTool.gd"))
	WhiteboardManager.register_tool(preload("ImageTool.gd"))
	WhiteboardManager.register_tool(preload("TextTool.gd"))
