@abstract class_name WhiteboardTool

## Hints that the inspector display should use the function specified by the
## [code]hint_string[/code] to generate a control rather than the built-in control
const PROPERTY_HINT_EXT_CUSTOM_INSPECTOR = 512


## Get a reverse-DNS (e.g. com.example.Tool) identifier specific to this tool.
static func get_id() -> StringName:
	assert(false)
	return ""


## Whether the tool is visible to the user.
## [br]
## Defaults to [code]true[/code].
static func is_visible() -> bool: return true

## The default shortcut of this tool, or [code]null[/code] for no shortcut.
## The user can customize it in the shortcuts menu.
## [br]
## Defaults to [code]null[/code].
static func get_shortcut() -> InputEvent: return null

## Called whenever the whiteboard receives a GUI input. [param event] is transformed by the
## whiteboard's draw transformation. Returns a [WhiteboardTool.Display] holding the list of new
## elements to create and new preview elements to draw.
@abstract func receive_input(wb: Whiteboard, event: InputEvent) -> Display

## Called when the tool is activated.
func activated(wb: Whiteboard) -> void: Util.unused(wb)

## This should return a constant value of whether the mouse should be hidden when this tool is
## active.
## [br]
## Defaults to [code]true[/code].
func should_hide_mouse() -> bool: return false

## A single element to be drawn to a [Whiteboard].
@abstract class Element:
	## Get a reverse-DNS (e.g. com.example.Tool) identifier specific to this tool
	static func get_id() -> StringName:
		assert(false)
		return ""

	## Called when [param canvas] needs to be redrawn. Use the properties of [param wb] to do so,
	## but don't draw to it.
	@abstract func draw(canvas: Whiteboard.ElementLayer, wb: Whiteboard) -> void

	## The bounding box of this element (ununsed currently)
	@abstract func get_bounding_box() -> Rect2

	## Gets this element's properties serialized to a [Dictionary]. This dictionary is then
	## serialized in the save file.
	@abstract func serialize() -> Dictionary

	## Deserialize a dictionary to an [Element] from a dictionary generated by [method serialize].
	static func deserialize(data: Dictionary) -> Element:
		Util.unused(data)
		assert(false)
		return null

## A single element to be drawn to the preview layer of a [Whiteboard].
@abstract class PreviewElement:
	## Called when [param canvas] needs to be redrawn. Use the properties of [param wb] to do so,
	## but don't draw to it.
	@abstract func draw(canvas: CanvasItem, wb: Whiteboard)


## A single element to be drawn to the static preview layer of a [Whiteboard].
## The static preview layer works like the regular preview layer, but it doeesn't get transformed by
## the [Whiteboard]'s draw transformation.
@abstract class StaticPreviewElement:
	## Called when [param canvas] needs to be redrawn. Use the properties of [param wb] to do so,
	## but don't draw to it.
	@abstract func draw(wb: Whiteboard)

## A basic preview element that draws a circle at the given [member position] given a [member color]
## and [member width].
class PlainPreviewElement extends WhiteboardTool.PreviewElement:
	var position: Vector2
	var color: Color
	var width: float

	func draw(canvas: CanvasItem, _wb: Whiteboard) -> void:
		canvas.draw_circle(position, width * 0.5, color, false, 1.0 / _wb.draw_scale)


class Display:
	var elements: Array[Element]
	var preview_elements: Array[PreviewElement]
	var static_preview_elements: Array[StaticPreviewElement]
	var cursor_shape: Control.CursorShape

	func _init(_elements: Array[Element] = [], _preview_elements: Array[PreviewElement] = [], _static_preview_elements: Array[StaticPreviewElement] = []) -> void:
		elements = _elements
		preview_elements = _preview_elements
		static_preview_elements = _static_preview_elements


	func with_cursor_shape(_cursor_shape: Control.CursorShape) -> Display:
		cursor_shape = _cursor_shape
		return self
